import Head from 'next/head'


export default function Home({posts}) {
  return (
    <div style={{marginTop:"3rem",marginBottom:'3rem'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='title'>Home</h1>
      <h2>User List</h2>
      {posts?.map((user)=>(
        <div key={user.id}>
          {user.id}-{user.name}
        </div>
      ))}
    </div>
  )
}

export const getServerSideProps =async()=>{
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const posts=await res.json();

  return {
    props:{
      posts,
    }
  }
}